### ISSUE TITLE
Compatibility with Lincoln Stopped After 1.26

### ISSUE THREAD

**Issue by 951ryan** [itchannel/fordpass-ha#145]
I have the FordPass integration working on Home Assistant with v1.26 working just fine for my 2020 Lincoln Aviator.  Everything works including the fuel, remote start, doors & windows.   Once v1.27 and now v1.28 the integration stopped working and upon trying to download and login again it says the vin is not found on my account (I tried both the Fordpass & Lincoln logins).  As soon as I downgraded to v1.26 and used the same logins as Lincoln-Way I the integration started working again so something with 1.27-1.28 caused this to break.

Home Assistant OS 7.0
core-2021.12.3
supervisor-2021.12.2

**Comment by itchannel** [comment]
I think I know the issue as I implemented a check against user VIN's on a persons account but didn't realise the lincoln app logins work so it's probably not in the array. 

Any chance you can add the following debug and then send me the log of fordpass so I can see if your vehicle shows in the vehicle list at all or whether I have to remove the check/add an override.

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

**Comment by 951ryan** [comment]
Attached is the debug log.  I simply edited my vin with a fake # for privacy but the rest is untouched.

[Debug Log](https://github.com/itchannel/fordpass-ha/files/7738227/Debug.Log)

**Comment by itchannel** [comment]
Is that the old version? Do you mind just trying with the new version so I can get the VIN error.

**Comment by colings** [comment]
My FordPass seems to have been broken for a while too, I also have a 2020 Aviator. I tried deleting it and readding it and it didn't fix it. Here's the log I get:
- DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 3.350 seconds (success: False)
- DEBUG (MainThread) [custom_components.fordpass] North America & Canada
- DEBUG (MainThread) [custom_components.fordpass] password
- DEBUG (MainThread) [custom_components.fordpass] region
- DEBUG (MainThread) [custom_components.fordpass] username
- DEBUG (MainThread) [custom_components.fordpass] vin
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] 401 response stage 2: refresh stage 1 token
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] 401 response stage 2: refresh stage 1 token
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] 401 response stage 2: refresh stage 1 token
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] 401 with status request: start token refresh
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Succesfully fetched token Stage1
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Succesfully fetched token Stage1
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Succesfully fetched token Stage1
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Token is valid, continuing
- DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Token is valid, continuing
- ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for MY_VIN
- WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for MY_VIN
- WARNING (MainThread) [custom_components.fordpass] local variable 'result' referenced before assignment

**Comment by colings** [comment]
FYI, I just tried this again today on 1.30 and it worked fine. I'm not sure if there was an update since last time I tried or it was magically fixed, but it's all good now. Thanks @itchannel
